(ns fzgx-names-cljs.core
  (:refer-clojure :exclude [== name])
  (:use-macros [cljs.core.logic.macros :only [run* == fresh]])
  (:require-macros [cljs.core.logic.macros :as m]
                   [cljs.core.logic.pldb :as pldb])
  (:require [cljs.core.logic.pldb :as pldb]))


(pldb/db-rel body p)
(pldb/db-rel cockpit p)
(pldb/db-rel booster p)
(pldb/db-rel name body cockpit booster p)

(def facts
  (pldb/db
   [body "Splash Wh."]
   [body "Optical W."]
   [body "Liberty M."]
   [body "Funny Sw. "]
   [body "Optical W."]
   [body "Speedy Dr."]
   [body "Funny Sw. "]
   [body "Holy Sp.  "]
   [body "Rapid Bar."]
   [body "Silver Sw."]
   [body "Aqua Goose"]
   [body "Space Can."]
   [body "Liberty M."]
   [body "Rapid Bar."]
   [body "Sky Horse "]
   [body "Space Can."]
   [body "Sky Horse "]
   [body "Wild Char."]
   [body "Silver Sw."]
   [body "Fire Wolf "]
   [body "Giant Pl. "]
   [body "Valiant J."]
   [body "Valiant J."]
   [body "Fire Wolf "]
   [body "Mad Bull  "]
   [body "Valiant J."]
   [body "Aqua Goose"]
   [body "Fire Wolf "]
   [body "Dread Ha. "]
   [body "Big Tyrant"]
   [body "Rapid Bar."]
   [body "Big Tyrant"]
   [body "Dread Ha. "]
   [body "Megalo Cr."]
   [body "Dread Ha. "]
   [body "Aqua Goose"]
   [body "Grand Base"]
   [body "Big Tyrant"]
   [body "Dread Ha. "]
   [body "Megalo Cr."]
   [body "Grand Base"]
   [cockpit "Crystal E."]
   [cockpit "Moon Snail"]
   [cockpit "Sonic So. "]
   [cockpit "Windy Sh. "]
   [cockpit "Dark Ch.  "]
   [cockpit "Red Rex   "]
   [cockpit "Cyber Fox "]
   [cockpit "Garnet Ph."]
   [cockpit "Heat Snake"]
   [cockpit "Bright Sp."]
   [cockpit "Heat Snake"]
   [cockpit "Bright Sp."]
   [cockpit "Scud Viper"]
   [cockpit "Wonder Wo."]
   [cockpit "Heat Snake"]
   [cockpit "Aerial Bu."]
   [cockpit "Wonder Wo."]
   [cockpit "Garnet Ph."]
   [cockpit "Cyber Fox "]
   [cockpit "Dark Ch.  "]
   [cockpit "Scud Viper"]
   [cockpit "Blast Cam."]
   [cockpit "Spark Bird"]
   [cockpit "Rave Dr.  "]
   [cockpit "Moon Snail"]
   [cockpit "Spark Bird"]
   [cockpit "Bright Sp."]
   [cockpit "Heat Snake"]
   [cockpit "Rave Dr.  "]
   [cockpit "Spark Bird"]
   [cockpit "Rave Dr.  "]
   [cockpit "Muscle Go."]
   [cockpit "Crazy Bu. "]
   [cockpit "Garnet Ph."]
   [cockpit "Sonic So. "]
   [cockpit "Garnet Ph."]
   [cockpit "Dark Ch.  "]
   [cockpit "Rave Dr.  "]
   [cockpit "Combat Ca."]
   [cockpit "Blast Cam."]
   [cockpit "Energy Cr."]
   [cockpit "Crystal E."]
   [cockpit "Rave Dr.  "]
   [cockpit "Combat Ca."]
   [cockpit "Sonic So. "]
   [cockpit "Muscle Go."]
   [cockpit "Crazy Bu. "]
   [cockpit "Rave Dr.  "]
   [cockpit "Energy Cr."]
   [cockpit "Super Lynx"]
   [cockpit "Spark Bird"]
   [cockpit "Aerial Bu."]
   [cockpit "Crazy Bu. "]
   [cockpit "Combat Ca."]
   [booster "Comet -V"]
   [booster "Impulse"]
   [booster "Jupiter"]
   [booster "Bazooka"]
   [booster "Saturn"]
   [booster "Jupiter"]
   [booster "Impulse"]
   [booster "Euros -01"]
   [booster "Euros -01"]
   [booster "Raiden"]
   [booster "Triangle"]
   [booster "Boxer -2C"]
   [booster "Bluster"]
   [booster "Triangle"]
   [booster "Euros -01"]
   [booster "Scorpion"]
   [booster "Triangle"]
   [booster "Jupiter"]
   [booster "Impulse"]
   [booster "Scorpion"]
   [booster "Triple -Z"]
   [booster "Raiden"]
   [booster "Impulse"]
   [booster "Meteor"]
   [booster "Titan -G4"]
   [booster "Euros -01"]
   [booster "Punisher"]
   [booster "Impulse"]
   [booster "Bluster"]
   [booster "Euros -01"]
   [booster "Extreme"]
   [booster "Titan -G4"]
   [booster "Mars -EX"]
   [booster "Sunrise"]
   [booster "Devilfish"]
   [booster "Boxer -2C"]
   [booster "Sunrise"]
   [booster "Bazooka"]
   [booster "Devilfish"]
   [booster "Bazooka"]
   [booster "Sunrise"]
   [booster "Saturn"]
   [booster "Meteor"]
   [booster "Thunder."]
   [booster "Meteor"]
   [booster "Boxer -2C"]
   [booster "Impulse"]
   [booster "Meteor"]
   [booster "Jupiter"]
   [booster "Titan -G4"]
   [booster "Extreme"]
   [booster "Thunder."]
   [booster "Punisher"]
   [booster "Thunder."]
   [name "Splash Wh." "Crystal E." "Comet -V" "Queen Sapphire"]
   [name "Optical W." "Moon Snail" "Impulse" "Bird Of Paradise"]
   [name "Liberty M." "Sonic So. " "Jupiter" "Ground Wave"]
   [name "Funny Sw. " "Windy Sh. " "Bazooka" "Out Rider"]
   [name "Funny Sw. " "Dark Ch.  " "Saturn" "Icarus Wing"]
   [name "Optical W." "Red Rex   " "Jupiter" "Fortissimo"]
   [name "Optical W." "Cyber Fox " "Impulse" "Trickster"]
   [name "Speedy Dr." "Garnet Ph." "Euros -01" "Paper Craft"]
   [name "Optical W." "Heat Snake" "Euros -01" "Savanna Buggy"]
   [name "Speedy Dr." "Bright Sp." "Raiden" "Dragoon"]
   [name "Splash Wh." "Heat Snake" "Triangle" "Red Salamander"]
   [name "Funny Sw. " "Bright Sp." "Boxer -2C" "Gargoyle"]
   [name "Funny Sw. " "Scud Viper" "Bluster" "Liberator"]
   [name "Holy Sp.  " "Wonder Wo." "Triangle" "Blue Streak"]
   [name "Holy Sp.  " "Heat Snake" "Euros -01" "Carbunkle"]
   [name "Rapid Bar." "Aerial Bu." "Scorpion" "Long Shot"]
   [name "Silver Sw." "Wonder Wo." "Triangle" "Enigma"]
   [name "Optical W." "Garnet Ph." "Jupiter" "Valkyrie"]
   [name "Aqua Goose" "Cyber Fox " "Impulse" "Splash Mermaid"]
   [name "Space Can." "Dark Ch.  " "Scorpion" "Astro Scorpion"]
   [name "Liberty M." "Scud Viper" "Triple -Z" "Fantasista"]
   [name "Rapid Bar." "Blast Cam." "Raiden" "Salvation"]
   [name "Sky Horse " "Spark Bird" "Impulse" "Emerald Pegasus"]
   [name "Space Can." "Rave Dr.  " "Meteor" "Hermit Crab"]
   [name "Sky Horse " "Moon Snail" "Titan -G4" "Master Work"]
   [name "Wild Char." "Spark Bird" "Euros -01" "Centaurus"]
   [name "Silver Sw." "Bright Sp." "Punisher" "Alexander"]
   [name "Fire Wolf " "Heat Snake" "Impulse" "Liberty Triton"]
   [name "Giant Pl. " "Rave Dr.  " "Bluster" "Super Nova"]
   [name "Valiant J." "Spark Bird" "Euros -01" "Triumph"]
   [name "Valiant J." "Rave Dr.  " "Extreme" "Grand Elephant"]
   [name "Fire Wolf " "Muscle Go." "Titan -G4" "Beat The Beast"]
   [name "Mad Bull  " "Crazy Bu. " "Mars -EX" "Bahamut"]
   [name "Valiant J." "Garnet Ph." "Sunrise" "Scorcher"]
   [name "Aqua Goose" "Sonic So. " "Devilfish" "Aqua Griffin"]
   [name "Fire Wolf " "Garnet Ph." "Boxer -2C" "Fire Ball"]
   [name "Dread Ha. " "Dark Ch.  " "Sunrise" "Leviathan"]
   [name "Big Tyrant" "Rave Dr.  " "Bazooka" "High Roller"]
   [name "Rapid Bar." "Combat Ca." "Devilfish" "Eliminator"]
   [name "Big Tyrant" "Blast Cam." "Bazooka" "Desert Camel"]
   [name "Dread Ha. " "Energy Cr." "Sunrise" "Trailblazer"]
   [name "Megalo Cr." "Crystal E." "Saturn" "Hippopotamus"]
   [name "Dread Ha. " "Rave Dr.  " "Meteor" "Poseidon"]
   [name "Aqua Goose" "Combat Ca." "Thunder." "Van Guard"]
   [name "Grand Base" "Sonic So. " "Meteor" "Bandersnatch"]
   [name "Big Tyrant" "Muscle Go." "Boxer -2C" "Sockdolager"]
   [name "Dread Ha. " "Crazy Bu. " "Impulse" "Notorious Gear"]
   [name "Megalo Cr." "Rave Dr.  " "Meteor" "Big Ace"]
   [name "Megalo Cr." "Energy Cr." "Jupiter" "Don Quixote"]
   [name "Grand Base" "Super Lynx" "Titan -G4" "King Neptune"]
   [name "Grand Base" "Spark Bird" "Extreme" "Almagest"]
   [name "Grand Base" "Aerial Bu." "Thunder." "Nightmare"]
   [name "Dread Ha. " "Crazy Bu. " "Punisher" "Final Revolution"]
   [name "Megalo Cr." "Combat Ca." "Thunder." "Hard Banger"]))

(defn ^:export search-body
  [part]
  (pldb/with-db facts
  (doall
   (run* [q]
        (fresh [body-part cockpit-part booster-part ship-name]
               (== body-part part)
               (name body-part cockpit-part booster-part ship-name)
               (== q [body-part cockpit-part booster-part ship-name]))))))

(defn ^:export search-cockpit
    [part]
  (pldb/with-db facts
  (doall
   (run* [q]
        (fresh [body-part cockpit-part booster-part ship-name]
               (== cockpit-part part)
               (name body-part cockpit-part booster-part ship-name)
               (== q [body-part cockpit-part booster-part ship-name]))))))

(defn ^:export search-booster
    [part]
  (pldb/with-db facts
  (doall
   (run* [q]
        (fresh [body-part cockpit-part booster-part ship-name]
               (== booster-part part)
               (name body-part cockpit-part booster-part ship-name)
               (== q [body-part cockpit-part booster-part ship-name]))))))

(defn ^:export name-from-parts
    [find-body find-cockpit find-booster]
  (pldb/with-db facts
  (doall
   (run* [q]
        (fresh [body-part cockpit-part booster-part ship-name]
               (== body-part find-body)
               (== cockpit-part find-cockpit)
               (== booster-part find-booster)
               (name body-part cockpit-part booster-part ship-name)
               (== q ship-name))))))
